version: '3'
services:
  portal:
    ports:
      - "80:80"
    image: "icdocsoc/portal:latest"
    network_mode: "host"
    volumes:
      - /portal/sponsors:/portal/sponsors
      - /portal/secure:/portal/secure
      - /portal/logs:/portal/logs
    restart_policy:
      condition: on-failure
